name: kaggle
channels:
    - default
dependencies:
    - jupyterlab=2.2.6
    - matplotlib
    - numpy
    - pandas
    - pyarrow=2.0.0
    - python=3.8
    - scipy
    - scikit-learn
    - seaborn
    - statsmodels